export const LEAD_REPLY_TYPE_NONE = 'NONE';
export const LEAD_REPLY_TYPE_SMS_REPLY = 'SMS_REPLY';
export const LEAD_REPLY_TYPE_SMS_REPLY_CONTAIN = 'SMS_REPLY_CONTAIN';
export const LEAD_REPLY_TYPE_MAIL_OPEN = 'MAIL_OPEN';
